# -*- coding: utf-8 -*-
"""Copy of Proyek Analisis Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQFEdgQgL1vd_2VKBvzdPJncLZVu9VL_

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Maulana Wirawan
- **Email:** awan.maraikoh@gmail.com
- **ID Dicoding:** Maulana Wirawan

# Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from scipy.stats import pearsonr
from sklearn.cluster import KMeans

"""# Mount Google Drive

"""

drive.mount('/content/drive')

"""## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Apakah ada korelasi antara suhu (TEMP) dan kualitas udara (PM2.5)?

- Pertanyaan 2 : Bagaimana tren kualitas udara (PM2.5) sepanjang waktu?

# Data Wrangling

## Gathering Data

### Setelah proses mounting selesai
"""

data = pd.read_csv('/content/drive/MyDrive/analisis python dicoding bangkit/Air-quality-dataset/PRSA_Data_20130301-20170228/PRSA_Data_Aotizhongxin_20130301-20170228.csv')
data.head()

"""### Assessing Data

#### Melakukan penilaian awal terhadap data
"""

data.info()

data.describe()

"""### Cleaning Data

#### Melakukan pembersihan dan penyiapan data untuk analisis

### Menampilkan jumlah baris dan kolom sebelum drop
"""

print("Sebelum drop:")
print("Jumlah baris:", data.shape[0])
print("Jumlah kolom:", data.shape[1])

"""### Drop data

"""

data = data.dropna()

"""### Menampilkan jumlah baris dan kolom setelah drop

"""

print("\nSetelah drop:")
print("Jumlah baris:", data.shape[0])
print("Jumlah kolom:", data.shape[1])

"""## Exploratory Data Analysis (EDA)

### Explore ...

### Melakukan eksplorasi data untuk mendapatkan insight awal

### Menampilkan statistik deskriptif dari data
"""

print(data.describe())

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Apakah ada korelasi antara suhu (TEMP) dan kualitas udara (PM2.5)?

### Melakukan visualisasi dan analisis untuk menjawab pertanyaan 1
"""

plt.figure(figsize=(10, 6))
plt.scatter(data['TEMP'], data['PM2.5'])
plt.title('Korelasi antara Suhu dan PM2.5')
plt.xlabel('Suhu')
plt.ylabel('PM2.5')A
plt.show()

"""# Menghitung koefisien korelasi Pearson

"""

corr, _ = pearsonr(data['TEMP'], data['PM2.5'])
print('Koefisien Korelasi Pearson antara Suhu dan PM2.5: %.3f' % corr)

"""### Pertanyaan 2: Bagaimana tren kualitas udara (PM2.5) sepanjang waktu?

### Melakukan visualisasi dan analisis untuk menjawab pertanyaan 2
"""

data['date'] = pd.to_datetime(data[['year', 'month', 'day', 'hour']])
data.set_index('date', inplace=True)

data['PM2.5'].resample('M').mean().plot(figsize=(10, 6))
plt.title('Tren Kualitas Udara (PM2.5) Sepanjang Waktu')
plt.ylabel('PM2.5')
plt.show()

"""# Menerapkan teknik analisis lanjutan seperti clustering

### Menggunakan KMeans untuk mengelompokkan data berdasarkan suhu dan PM2.5
"""

kmeans = KMeans(n_clusters=3, random_state=0).fit(data[['TEMP', 'PM2.5']])
data['cluster'] = kmeans.labels_

"""# Visualisasi hasil clustering

"""

plt.figure(figsize=(10, 6))
plt.scatter(data['TEMP'], data['PM2.5'], c=data['cluster'])
plt.title('Hasil Clustering Berdasarkan Suhu dan PM2.5')
plt.xlabel('Suhu')
plt.ylabel('PM2.5')
plt.show()

"""## Conclusion

- Conclution pertanyaan 1:
Berdasarkan analisis yang telah dilakukan, berikut adalah kesimpulan untuk pertanyaan 1:

Dari visualisasi dan koefisien korelasi Pearson sebesar -0.126, dapat disimpulkan bahwa ada korelasi negatif yang lemah antara suhu (TEMP) dan kualitas udara (PM2.5). Artinya, ketika suhu sedikit menurun, PM2.5 sedikit meningkat, dan sebaliknya. Namun, perlu diingat bahwa korelasi ini lemah dan mungkin tidak signifikan secara statistik.

Meskipun ada korelasi antara suhu dan PM2.5, ini tidak berarti bahwa perubahan suhu menyebabkan perubahan dalam PM2.5, atau sebaliknya. Mungkin ada faktor lain yang mempengaruhi keduanya. Selain itu, data ini mungkin tidak mencerminkan pola yang sama di lokasi lain atau pada waktu yang berbeda. Selalu penting untuk memahami konteks dan batasan data Anda saat melakukan analisis data.



- Conclution pertanyaan 2
Berdasarkan analisis yang telah dilakukan, berikut adalah kesimpulan untuk pertanyaan 2:


2014-2015: Tren PM2.5 relatif stabil.
2016-2017: Tren PM2.5 menunjukkan peningkatan yang signifikan pada February 2014, December 2015, dan December 2016.

Berdasarkan data yang tersedia, tren kualitas udara (PM2.5) menunjukkan peningkatan yang mengkhawatirkan sepanjang waktu.

# Tambahan

# Analisis Korelasi Seluruh Variabel
"""

corr = data.corr()
plt.figure(figsize=(10, 10))
sns.heatmap(corr, annot=True, square=True, cmap='coolwarm')
plt.title('Korelasi antara Semua Variabel')
plt.show()

"""# Analisis Outlier"""

plt.figure(figsize=(15, 10))
data.boxplot()
plt.title('Boxplot untuk Setiap Variabel')
plt.show()

"""# Analisis Time Series"""

data.resample('M').mean().plot(subplots=True, figsize=(10, 12))
plt.title('Tren Setiap Variabel Sepanjang Waktu')
plt.show()

"""# Analisis Clustering Lanjutan"""

from sklearn.decomposition import PCA
from mpl_toolkits.mplot3d import Axes3D

"""### Melakukan PCA untuk mengurangi dimensi data

"""

pca = PCA(n_components=3)
data_pca = pca.fit_transform(data[['TEMP', 'PM2.5', 'PRES']])

"""### Melakukan clustering

"""

kmeans = KMeans(n_clusters=3, random_state=0).fit(data_pca)
labels = kmeans.labels_

"""### Membuat plot 3D

"""

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(data_pca[:, 0], data_pca[:, 1], data_pca[:, 2], c=labels)
plt.title('Hasil Clustering dengan PCA')
plt.show()